// import 'package:loginpage/sadacedart/ders.dart';

// class Strings {
//   static const List<String> DERS_ADLARI = [
//   "Tarih",                                                                              
//   'Coğrafya',
//   "Matematik",
//   "Geometri",
//   "Fizik",
//   "Kimya",
//   "Biyoloji",
//   "Din Kültürü ve Ahlak Bilgisi",
//   "Felsefe",
//   "Türkçe",
//   ];

// static const List<String> DERS_GENEL_OZELLIKLERI = [
  
//   "\tTarih Bilimi\n\n"
//   "\tUygarlığın Doğuşu ve İlk Uygarlıklar\n\n"
//   "\tİlk Türk Devletleri\n\n"
//   "\tİslam Tarihi ve Uygarlığı (13. Yüzyıla kadar\n\n"
//   "\tTürk-İslam Devletleri(10-13. Yüzyıllar\n\n"
//   "\tOrtaçağ'da Avrupa\n\n"
//   "\tTürkiye Tarihi(11-13.Yüzyıllar)\n\n"
//   "\tBeylikten Devlete(1300-1453<3)\n\n"
//   "\tDünya Gücü: Osmanlı Devleti (1453-1600) \n\n"
//   "\tYeniçağ ve Yakınçağ'da Avrupa\n\n"
//   "\tOsmanlı'da Arayış Yılları (1600-1700)\n\n"
//   "\tXVIII. Yüzyılda Değişim ve Diplomasi\n\n"
//   "\tEn Uzun Yüzyıl (1800-1922) \n\n"
//   "\tOsmanlı Devleti'nin Kültür ve Medeniyeti\n\n"
//   "\tTrablusgarp Savaşı ve Balkan Savaşları\n\n"
//   "\tI.Dünya Savaşı ve Sonrası Gelişmeler\n\n"
//   "\tKurtuluş Savaşı Hazırlık Dönemi\n\n"
//   "\tTBMM'nin Açılması ve Ayaklanmalar\n\n"
//   "\tKurtuluş Savaşın'da Cephaneler  ve Antlaşmalar\n\n"
//   "\tCumhuriyet Dönemi İnkılapları\n\n"
//   "\tAtatürkçü Düşünce Sistemi ve Atatürkçülük\n\n"
//   "\tAtatürk Dönemi Türk Dış Politikası\n\n"
//   "\tÇok Partili Hayata Geçiş\n\n"
//   "\tII.Dünya Savaşı (1939-1945)\n\n"
//   "\tSoğuk Savaş Dönemi\n\n"
//   "\tKüreselleşen Dünya\n\n"
//   "\tYönetim Biçimleri\n\n",

//   "\tTürkiye'nin Beşeri Coğrafyası\n\n"
//   "\tDünyanın Şekli ve Haraketleri\n\n"
//   "\tHarita Bilgisi\n\n"
//   "\tSıcaklık\n\n"
//   "\tBasınç ve Rüzgarlar\n\n"
//   "\tNem ve Yağışlar\n\n"
//   "\tİç Kuvvetler ve Olaylar\n\n"
//   "\tDış Kuvvetler ve Olaylar\n\n"
//   "\tTürkiye'nin Fiziki Coğrafyası\n\n"
//   "\tÇevre ve Toplum\n\n"
//   "\tSu, Toprak ve Bitki Varlığı\n\n"
//   "\tTürkiye'de Tarım ve Hayvancılık\n\n"
//   "\tTürkiye'de Madenler ve Enerji Kaynakları\n\n"
//   "\tBölge Kavramı, Bölgeler ve Özellikleri\n\n"
//   "\tUluslararası Örgütler ve Ülkeler\n\n"
//   "\tİnsan, Doğa ve Coğrafya\n\n"
//   "\tCoğrafi Konum\n\n"
//   "\tİklim Bilgisi-Hava Durumu-Atmosfer\n\n"
//   "\tYer YApısı\n\n"
//   "\tNufüs ve Yerleşme,Göçler\n\n"
//   "\tEkonomik Faaliyetler ve Doğal Kaynaklar\n\n"
//   "\tDünayayı Birbirine Bağlayan Ağlar: Ulaşım\n\n"
//   "\tDoğal Afetler\n\n"
//   "\tEkosistem ve Madde Döngüleri\n\n"
//   "\tDoğadaki Ekstrem Olaylar ve Etkileri\n\n"
//   "\tTürkiye'de Sanayi ve Hizmet\n\n"
//   "\tTürk Kültürü & Kültür Bölgeleri\n\n"
//   "\tKüresel Ticaret & Turizm\n\n",

//   "\tAsal Çarpanlar ve Tam Bölenler\n\n"
//   "\tBasamak Kavramı\n\n"
//   "\tTaban Aritmetiği\n\n"
//   "\tBölme-Bölünebilme\n\n"
//   "\tEBOB-EKOK\n\n"
//   "\tRasyonel Sayılar\n\n"
//   "\tMutlak Değer\n\n"
//   "\tFaktöriyel\n\n"
//   "\tÜslü ifadeler\n\n"
//   "\tKöklü Sayılar\n\n"
//   "\tÇarpanlara Ayırma\n\n"
//   "\tBasit Eşitsizlikler\n\n"
//   "\tMantık\n\n"
//   "\tKümelerde İşlemler\n\n"
//   "\tKümelerde Problemler\n\n"
//   "\tBaağıntı ve Sıralı İkili\n\n"
//   "\tKartezyen Çarpım\n\n"
//   "\tFonksiyonlar\n\n"
//   "\tOran-Orantı\n\n"
//   "\tDenklem Kurma\n\n"
//   "\tSayı Problemleri\n\n"
//   "\tYüzde Problemleri\n\n"
//   "\tYaş Problemleri\n\n"
//   "\tYaş Problemleri\n\n"
//   "\tİşçi-Havuz Problemleri\n\n"
//   "\tFaiz Problemleri\n\n"
//   "\tHareket Problemleri\n\n"
//   "\tKar-Zarar Problemleri\n\n"
//   "\tKarışım Problemleri\n\n"
//   "\tİşlemn\n"
//   "\tModüler Aritmetik\n\n"
//   "\tPolinom\n\n"
//   "\t2.Dereceden Denklemler\n\n"
//   "\t2.Dereceden Eşitsilikler\n\n"
//   "\tParabol\n\n"
//   "\tPermütasyon\n\n"
//   "\tKombinasyon\n\n"
//   "\tBinom\n\n"
//   "\tOlasılık\n\n"
//   "\tVeri Analizi-İstatistik\n\n"
//   "\tTrigonometrik Fonksiyonlar\n\n"
//   "\tTers Trigonometrik Fonksiyonlar\n\n"
//   "\tKosinüs-Sinüs teoremleri\n\n"
//   "\tTrig.Toplam-Fark Formülleri\n\n"
//   "\tTrig.Dönüşüm Formulleri\n\n"
//   "\tKarmaşık Sayılar\n\n"
//   "\tLogaritmanın Kuralları\n\n"
//   "\tLogaritmik eşitsizlikler\n\n"
//   "\tLogaritmanın Grafiği\n\n"
//   "\tToplam ve Çarpım Sembolü\n\n"
//   "\tGerçek Sayı Dizileri\n\n"
//   "\tSeriler\n\n"
//   "\tBirinci Dereceden Denklemler ve Eşitsilikler\n\n"
//   "\tÖzel Tanımlı Fonksiyonlar\n\n"
//   "\tLimit ve Süreklilik\n\n"
//   "\tTürev Alma\n\n"
//   "\tArtan ve Azalan Fonksiyonlar\n\n"
//   "\tEkstremum Noktaları\n\n"
//   "\tMaks.-Min.Problemleri\n\n"
//   "\tİntegral Alma Kuralları\n\n"
//   "\tİntegralde Alan\n\n"
//   "\tDenklem Çözme\n\n"
//   "\tKesir Problemleri\n\n"
//   "\tTrigonometri\n\n"
//   "\tTürevin Geometrik Yorumu\n\n"
//   "\tRutin Olmayan Problemler\n\n",

//   "\tTrigonometri\n\n"
//   "\tDoğruda Açılar\n\n"
//   "\tÜçgende Açılar\n\n"
//   "\tAçı-Kenar Bağıntıları\n\n"
//   "\tAçıortay ve Kenarortay\n\n"
//   "\tDik Üçgen\n\n"
//   "\tİkizkenar Üçgen\n\n"
//   "\tEşkenar Üçgen\n\n"
//   "\tÜçgende Benzerlik\n\n"
//   "\tÜçgende Alan\n\n"
//   "\tÇokgenler\n\n"
//   "\tDörtgenler\n\n"
//   "\tYamuk\n\n"
//   "\tParalelkenar\n\n"
//   "\tEşkenar Dörtgen-Deltoid\n\n"
//   "\tDikdörtgen\n\n"
//   "\tKare\n\n"
//   "\tÇemberde Açı\n\n"
//   "\tÇemberde Uzunluk\n\n"
//   "\tDairede Alan\n\n"
//   "\tKatı Cisimler\n\n"
//   "\tNoktanın Analitik İncelemesi\n\n"
//   "\tDoğrunun Analitik İncelemesi\n\n"
//   "\tÇemberin Analitik İncelemesi\n\n"
//   "\tKoniklerin Analitik İncelemesi\n\n"
//   "\tVektörler\n\n"
//   "\tDönüşüm Geometrisi\n\n"
//   "\tTrigonometrik Fonksiyonlar\n\n"
//   "\tTers Trigonometrik Fonksiyonlar\n\n"
//   "\tKosinüs-sinüs teoremleri\n\n"
//   "\tToplam-Fark ve İki Kat Açı Formülleri\n\n"
//   "\tTrig. Dönüşüm Formülleri\n\n",
  
//   "\tFiziğin Doğası\n\n"
//   "\tMadde ve Özellikleri\n\n"
//   "\tBirimler\n\n"
//   "\tVektör ve Kuvvet\n\n"
//   "\tMoment & Denge\n\n"
//   "\tAğırlık Merkezi\n\n"
//   "\tBasit Makinalar\n\n"
//   "\tYeryüzünde Hareket (Atışlar) \n\n"
//   "\tDoğrusal Hareket\n\n"
//   "\tDüzgün Dairesel Hareket\n\n"
//   "\tBasit Hormonik Hareket\n\n"
//   "\tKeppler Yasaları\n\n"
//   "\tİtme & Momentum\n\n"
//   "\tDinamik\n\n"
//   "\tİş,Güç & Enerji\n\n"
//   "\tIsı,Sıcaklık & Genleşme\n\n"
//   "\tBasınç-Katı\n\n"
//   "\tBasınç-Sıvı\n\n"
//   "\tBasınç-Gaz\n\n"
//   "\tSıvıların Kaldırma Kuvvetleri\n\n"
//   "\tElektrostatik\n\n"
//   "\tDirençlerin  Bağlanması\n\n"
//   "\tElektrik Akımı\n\n"
//   "\tLambalı Devreler\n\n"
//   "\tMıknatıslar\n\n"
//   "\tElektromanyetizma\n\n"
//   "\tGölge\n\n"
//   "\tAydınlanma\n\n"
//   "\tDüzlem Ayna\n\n"
//   "\tKüresel Ayna\n\n"
//   "\tKırılma & Renk\n\n"
//   "\tMerceler \n\n"
//   "\tYay Dalgaları\n\n"
//   "\tSu Dalgaları\n\n"
//   "\tSu Dalgalarında Girişim\n\n"
//   "\tSes Dalgaları\n\n"
//   "\tIşık Teorileri\n\n"
//   "\tIşığın Tanecik Modeli\n\n"
//   "\tParelel yüklü Levhalar\n\n"
//   "\tSığa ve Kondansatör\n\n"
//   "\tEMK ve Zıt EMK\n\n"
//   "\tElektromanyetik indüksiyon\n\n"
//   "\taltarnatif Akım\n\n"
//   "\tTransformatör\n\n"
//   "\tModern Fizik\n\n"
//   "\tEloktromanyetik Dalgalr\n\n"
//   "\tAtom Fiziği\n\n"
//   "\tAtom Fiziğine Giriş ve Radyoaktivite \n\n"
//   "\tFotoelektrik\n\n"
//   "\tElektronik\n\n"
//   "\tBağıl Hareket\n\n"
//   "\tElektrik Alan\n\n"
//   "\tElektiriksel Potansiyel Kuvvet\n\n",
  
//   "\tAtomun Yapısı ve Periyodik Sistem\n\n"
//   "\tKimyasal Bağlar\n\n"
//   "\tBileşikler\n\n"
//   "\tKimyasal Değişimler ve Tepkime Türleri\n\n"
//   "\tYaygın Günlük Hayat Kimyasalları\n\n"
//   "\tKarışımların Sınıflandırılması ve Ayrışması\n\n"
//   "\tÇözünürlük\n\n"
//   "\tHyatımızda Kimya\n\n"
//   "\tKimyasal Hesaplamalar ve Mol Kavramı\n\n"
//   "\tÇevre Kimyası\n\n"
//   "\tKİmyasal Türler Arası Etkileşimler\n\n"
//   "\tAmorf ve Kristal Katılar-Sıvıların Özellikleri\n\n"
//   "\tGazlar\n\n"
//   "\tHal Değişimleri ve Isı & Sıcaklık\n\n"
//   "\tÇözeltiler\n\n"
//   "\tKimyasal Tepkimelerde Enerji\n\n"
//   "\tReaksiyon Hızı\n\n"
//   "\tKimyasal Denge\n\n"
//   "\tSulu Çözeltilerde Denge\n\n"
//   "\tAsitler,Bazlar ve Tuzlar\n\n"
//   "\tRedoks Raksiyonları ve İstemlilik\n\n"
//   "\tElektrokimyasal Piller\n\n"
//   "\tElektroliz\n\n"
//   "\tOrganik Kimyaya Giriş\n\n"
//   "\tAlkanlar\n\n"
//   "\tAlkenler\n\n"
//   "\tAlkinler\n\n"
//   "\tAlkoller ve Eterler\n\n"
//   "\tAldehitler ve Ketonlar \n\n"
//   "\tKarboksili Asitler ve Esterler\n\n"
//   "\tAlifatik Amonyak Türevleri\n\n"
//   "\tAromatik Bileşikler\n\n"
//   "\tOrganik Reksiyonlar\n\n"
//   "\tİzomerlik\n\n"
//   "\tKimya Bilimi\n\n"
//   "\tKimyanın Temel Kanunları\n\n"
//   "\tDoğa ve Kimya\n\n",

//   "\tAtomun Yapısı ve Periyodik Sistem\n\n"
//   "\tKimyasal Bağlar\n\n"
//   "\tBileşikler\n\n"
//   "\tKimyasal Değişimler ve Tepkime Türleri\n\n"
//   "\tYaygın Günlük Hayat Kimyasalları\n\n"
//   "\tKarışımların Sınıflandırılması ve Ayrışması\n\n"
//   "\tÇözünürlük\n\n"
//   "\tHyatımızda Kimya\n\n"
//   "\tKimyasal Hesaplamalar ve Mol Kavramı\n\n"
//   "\tÇevre Kimyası\n\n"
//   "\tKİmyasal Türler Arası Etkileşimler\n\n"
//   "\tAmorf ve Kristal Katılar-Sıvıların Özellikleri\n\n"
//   "\tGazlar\n\n"
//   "\tHal Değişimleri ve Isı & Sıcaklık\n\n"
//   "\tÇözeltiler\n\n"
//   "\tKimyasal Tepkimelerde Enerji\n\n"
//   "\tReaksiyon Hızı\n\n"
//   "\tKimyasal Denge\n\n"
//   "\tSulu Çözeltilerde Denge\n\n"
//   "\tAsitler,Bazlar ve Tuzlar\n\n"
//   "\tRedoks Raksiyonları ve İstemlilik\n\n"
//   "\tElektrokimyasal Piller\n\n"
//   "\tElektroliz\n\n"
//   "\tOrganik Kimyaya Giriş\n\n"
//   "\tAlkanlar\n\n"
//   "\tAlkenler\n\n"
//   "\tAlkinler\n\n"
//   "\tAlkoller ve Eterler\n\n"
//   "\tAldehitler ve Ketonlar \n\n"
//   "\tKarboksili Asitler ve Esterler\n\n"
//   "\tAlifatik Amonyak Türevleri\n\n"
//   "\tAromatik Bileşikler\n\n"
//   "\tOrganik Reksiyonlar\n\n"
//   "\tİzomerlik\n\n"
//   "\tKimya Bilimi\n\n"
//   "\tKimyanın Temel Kanunları\n\n"
//   "\tDoğa ve Kimya\n\n",

// "\tAtomun Yapısı ve Periyodik Sistem\n\n"
//   "\tKimyasal Bağlar\n\n"
//   "\tBileşikler\n\n"
//   "\tKimyasal Değişimler ve Tepkime Türleri\n\n"
//   "\tYaygın Günlük Hayat Kimyasalları\n\n"
//   "\tKarışımların Sınıflandırılması ve Ayrışması\n\n"
//   "\tÇözünürlük\n\n"
//   "\tHyatımızda Kimya\n\n"
//   "\tKimyasal Hesaplamalar ve Mol Kavramı\n\n"
//   "\tÇevre Kimyası\n\n"
//   "\tKİmyasal Türler Arası Etkileşimler\n\n"
//   "\tAmorf ve Kristal Katılar-Sıvıların Özellikleri\n\n"
//   "\tGazlar\n\n"
//   "\tHal Değişimleri ve Isı & Sıcaklık\n\n"
//   "\tÇözeltiler\n\n"
//   "\tKimyasal Tepkimelerde Enerji\n\n"
//   "\tReaksiyon Hızı\n\n"
//   "\tKimyasal Denge\n\n"
//   "\tSulu Çözeltilerde Denge\n\n"
//   "\tAsitler,Bazlar ve Tuzlar\n\n"
//   "\tRedoks Raksiyonları ve İstemlilik\n\n"
//   "\tElektrokimyasal Piller\n\n"
//   "\tElektroliz\n\n"
//   "\tOrganik Kimyaya Giriş\n\n"
//   "\tAlkanlar\n\n"
//   "\tAlkenler\n\n"
//   "\tAlkinler\n\n"
//   "\tAlkoller ve Eterler\n\n"
//   "\tAldehitler ve Ketonlar \n\n"
//   "\tKarboksili Asitler ve Esterler\n\n"
//   "\tAlifatik Amonyak Türevleri\n\n"
//   "\tAromatik Bileşikler\n\n"
//   "\tOrganik Reksiyonlar\n\n"
//   "\tİzomerlik\n\n"
//   "\tKimya Bilimi\n\n"
//   "\tKimyanın Temel Kanunları\n\n"
//   "\tDoğa ve Kimya\n\n",

// "\tAtomun Yapısı ve Periyodik Sistem\n\n"
//   "\tKimyasal Bağlar\n\n"
//   "\tBileşikler\n\n"
//   "\tKimyasal Değişimler ve Tepkime Türleri\n\n"
//   "\tYaygın Günlük Hayat Kimyasalları\n\n"
//   "\tKarışımların Sınıflandırılması ve Ayrışması\n\n"
//   "\tÇözünürlük\n\n"
//   "\tHyatımızda Kimya\n\n"
//   "\tKimyasal Hesaplamalar ve Mol Kavramı\n\n"
//   "\tÇevre Kimyası\n\n"
//   "\tKİmyasal Türler Arası Etkileşimler\n\n"
//   "\tAmorf ve Kristal Katılar-Sıvıların Özellikleri\n\n"
//   "\tGazlar\n\n"
//   "\tHal Değişimleri ve Isı & Sıcaklık\n\n"
//   "\tÇözeltiler\n\n"
//   "\tKimyasal Tepkimelerde Enerji\n\n"
//   "\tReaksiyon Hızı\n\n"
//   "\tKimyasal Denge\n\n"
//   "\tSulu Çözeltilerde Denge\n\n"
//   "\tAsitler,Bazlar ve Tuzlar\n\n"
//   "\tRedoks Raksiyonları ve İstemlilik\n\n"
//   "\tElektrokimyasal Piller\n\n"
//   "\tElektroliz\n\n"
//   "\tOrganik Kimyaya Giriş\n\n"
//   "\tAlkanlar\n\n"
//   "\tAlkenler\n\n"
//   "\tAlkinler\n\n"
//   "\tAlkoller ve Eterler\n\n"
//   "\tAldehitler ve Ketonlar \n\n"
//   "\tKarboksili Asitler ve Esterler\n\n"
//   "\tAlifatik Amonyak Türevleri\n\n"
//   "\tAromatik Bileşikler\n\n"
//   "\tOrganik Reksiyonlar\n\n"
//   "\tİzomerlik\n\n"
//   "\tKimya Bilimi\n\n"
//   "\tKimyanın Temel Kanunları\n\n"
//   "\tDoğa ve Kimya\n\n",


//   // "\tCanlıların Ortak Özellikleri\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
//   // "\t\n\n"
  






// ];






// }

